#! /bin/bash

echo "Beginning Script"

PROJECT_PATH=/home/USER/Documents/proj_lagann_vid/dense
COLMAP_PATH=/home/USER/Documents/colmap/build

$COLMAP_PATH/src/exe/dense_mesher \
    		--input_path $PROJECT_PATH/point-cloud.ply \
    		--output_path $PROJECT_PATH/mesh_fig.ply \
		--DenseMapperOptions.patch_match_window_radius 1 \
		--DenseMapperOptions.patch_match_sigma_spatial 0.1 \
		--DenseMapperOptions.fusion_min_num_pixels 10 \
  		--DenseMapperOptions.fusion_max_num_pixels 100 \
		--DenseMapperOptions.patch_match_gpu_index 0
